import type { Metadata } from "next";
import { Geist, Geist_Mono, EB_Garamond } from "next/font/google";
import "./globals.css";
import Particles from "./_components/Particles";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
	variable: "--font-eb-garamond",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${ebGaramond.variable} antialiased `}
			>
				<header className=" min-h-10 bg-[#F5F5F5] justify-center items-center flex w-full  py-24">
					<div className="absolute w-full overflow-hidden md:block">
						<Particles />
					</div>
					<div className="flex-row  w-2/3 font-serif">
						<div className="flex-col items-start">
							<h1 className="text-6xl font-extrabold">Victor</h1>
							<h1 className="text-4xl tracking-tight -mt-4">Lima</h1>
							<div className=" flex flex-row w-full gap-2">
								<h1 className="text-xl tracking-tight -mt-2">
									Engenheiro de Software
								</h1>
							</div>
						</div>
						<div className="flex-col"></div>
					</div>
				</header>
				<main>{children}</main>
			</body>
		</html>
	);
}
